### ISSUE TITLE
Enhancement: Whitespace reflow utils master issue

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#3673]
### Description

There are too many other issues related to this and I think it makes sense to bring them all together, and track progress in one place.

This encompasses:
- `black`-like deterministic cli utility: #2436 (where a lot of discussion has gone into how we might achieve this).
- Smarter whitespace and line break treatment: #1839 #2466 #365
- Centralising and rationalising reflow functions: #1230 #946 
- Better indentation: #2867 #3705 #3865 #3691 #3978
- Indentation bugs in templated loops where solutions oscillate due to an if statement which behaves differently on each loop: #2677 #3185

The vision for success is:
- All reflow code works within the existing frameworks for safely editing templated files by utilising the existing `LintFix` functionality (we may isolate this more in the process but that's a bonus).
- All rules have central `reflow` utilities they can call on. These return `LintFix` objects (as above), which can then be returned by the rule as it's own suggestions.
- Reflow routines are recursive such that they can be applied to whole files or sections of files.
- There is a cli command `reflow` which wraps a version of this code and applies it to the whole file.

There are a few stages of delivering this:

- [x] Build out a vision of how to do this (see #3824)
- [x] Implement _spacing_ framework (see #3824)
- [x] Implement depth map to support indentation (see #3824)
- [x] Implement indentation within `ReflowSequence` (i.e. `L003`, `L002` & `L004`). #3942 
- [x] Implement line breaks (i.e. `L016`, potentially also `L036`). #4067
- [ ] Handle edge case: `L052` as a special case (probably using the `rebreak` logic) 
- [x] Handle edge case: `L007` & `L019` as special cases: #3847
- [x] Handle edge case: `L065` as special case (using `alone` probably). #3847 
- [x] Handle missed case: `L008` (seems very possible with current capability). #3908
- [ ] Handle missed case: `L009` (unless handled with `L052`).
- [ ] Handle keyword based (i.e. not _type_ based) line breaks: `L041`.
- [ ] Handle compulsory empty line rules: `L022`
- [ ] Bring `L050` into the `respace` logic (start of file).
- [ ] Build test harness (and potentially API method concurrently) to apply reflow code in a _rule-like_ harness.
- [ ] Blunt reflow harness which takes segments and according to some configuration generates appropriate `LintFix` objects to reflow it (probably with no newlines initially as per phase 1 here: https://github.com/sqlfluff/sqlfluff/issues/2436#issuecomment-1184627620).
- [ ] Add sensible optimisation of reflow to optimally split appropriately (including some heirachy and smarts on _where_ to split).
- [x] Update docs accordingly (probably removing the current README in the `utils.reflow` module). #3970 
- [ ] *before release*: Provide a migration guide for configs. (partially addressed by #3915)
- [ ] Fuzzy or chaotic testing of the reflow routines to check determinism (using `hypothesis` or similar).

**Comment by alanmcruickshank** [comment]
As brought up in #3824 - `L052` is a special case of respacing - much more like line breaks (because of the movement around comments). I suggest that this is a PR all on it's own because of the specific logic.

**Comment by alanmcruickshank** [comment]
As brought up in https://github.com/sqlfluff/sqlfluff/pull/3824#discussion_r973773467. This should allow operator precedence, @barrywhart.

> This hasn't mattered in the past, because we aren't evaluating the SQL, but it seems like the standard precedence could be useful for inserting line breaks. Then, the heuristic of "prefer line breaks higher in the parse tree" would handle this also.

```
Level | Operators
-- | -0
 1 | ~ (Bitwise NOT)
 2 | * (Multiplication), / (Division), % (Modulus)
 3 | + (Positive), - (Negative), + (Addition), + (Concatenation), - (Subtraction), & (Bitwise AND), ^ (Bitwise Exclusive OR), \| (Bitwise OR)
 4 | =, >, <, >=, <=, <>, !=, !>, !< (Comparison operators)
 5 | NOT
 6 | AND
 7 | ALL, ANY, BETWEEN, IN, LIKE, OR, SOME
 8 | = (Assignment)
```

**Comment by alanmcruickshank** [comment]
Not everything here is ticked off - but I think the intent is now complete. The last major thing here is #2436 which I'll track directly ready for release.

Otherwise job done, so I'm closing this.
