### ISSUE TITLE
2.0.0 Release Checklist

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#4030]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

#3970 kicked off the timeline for 2.0.0 by explicitly mentioning it in the docs. This issue lays out the things that need to happen before release.

# Why 2.0.0?

There are a few backward incompatible changes coming and planned, which should trigger a major release. Those are:
- Reflow (#3673 ). In particular because of the impacts on configuration and on the parse tree.
  - #3942
  - #4067
- `sqlfluff format`, planned in #2436.
- Reorganisation of rule codes and categories: #4031

# How should we go about the release?

We should merge things as incrementally as possible. Pre-releases are a good thing. But the first full release should contain all the breaking bits.

There *should be a migration guide*.

# What's the checklist:

Before release we need:
- [x] Reindent merged #3942 
- [x] A solution to long lines (L016). #4067 
- [x] Rules reorganised, especially once reflow is all sorted. Old ones removed. Nice deprecation warnings etc... (#4031)
- [x] `sqlfluff format` command, working and integrated with rules. #4473 
- [ ] Migration guide.
- [x] Fix for #3989
- [x] Fix for #3988 
- [x] DBT templater changes: #3976
- [x] Named config references where possible for rules (re convo between @alanmcruickshank and @pwildenhain ) #4465  #4470 

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)
