### ISSUE TITLE
SQLFluff fails on Rule L003 in CI but not locally (using pre-commit hooks)

### ISSUE THREAD

**Issue by christopherekfeldt** [sqlfluff/sqlfluff#4304]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When we run pre-commit locally we use SQLFluff as one of our hooks, but it seems that the rule L003 regarding indentation doesn't find everything it needs locally in comparison to when ran in our CI. The linting rule works locally in some way, but it doesn't seem to find all indentation faults. So the step in pre-commit is then passed locally but then fails in our CI jobs.

This is the script we run in Gitlab ci for pre-commit which uses SQLFLuff as one of its many hooks.

    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - SKIP=sqlfluff-fix,terraform_fmt pre-commit run --show-diff-on-failure --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --to-ref "$CI_COMMIT_SHA"

The logs look like this :

<img width="732" alt="image" src="https://user-images.githubusercontent.com/17338299/213677396-11a2884f-eb25-4fea-b584-a96649318c4b.png">

These are our pre-commit hook config:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/17338299/213677510-8c924c32-d392-4c76-9145-5e4201d55401.png">

### Expected Behaviour

We expect it to find all issues regarding L003 locally. Or that if it passes locally it should do the same in the CI.

Neither way, it causes a lot of double work now, having to go back and forth between the CI and the local branch to fix those errors that SQLFluff lint displays.

### Observed Behaviour

SQL code:

`
with c_hwcc as (
    select *
    from {{ source
	('foundlay__wholesale', 'h_wholesale_customer_crediting'
	) }}
),

c_swcc as (
    select *
    from {{ source
	('foundlay__wholesale', 's_wholesale_customer_crediting'
	) }}
  where
    crediting_reason != "LB"
    and
    credit_type != "I"
),

c_lwcci as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_crediting_item'
	) }}
),

c_lwccdlu as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_crediting_deliv_logistic_unit'
	) }}
),

c_lwccsklu as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_crediting_stock_keeping_logistic_unit'
	) }}
),

c_lwccs as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_crediting_soi'
	) }}
),

item as (
    select *
    from {{ source
	('foundlay__item', 'h_item'
	) }}
),

logistic_unit as (
    select *
    from {{ source
	('foundlay__logistic_unit', 'h_logistic_unit'
	) }}
),

store as (
    select *
    from {{ source
	('foundlay__store_orderable_item', 'h_store_orderable_item'
	) }}
),

i_hwcil as (
    select *
    from {{ source
	('foundlay__wholesale', 'h_wholesale_customer_invoice_line'
	) }}
),

i_lwcilds as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_line_deliv_soi'
	) }}
),

i_lwcil as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_line'
	) }}
),

i_lwciilu as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_invoicing_logistic_unit'
	) }}
),

i_swcil as (
    select *
    from {{ source
	('foundlay__wholesale', 's_wholesale_customer_invoice_line'
	) }}
),

i_swci as (
    select *
    from {{ source
	('foundlay__wholesale', 's_wholesale_customer_invoice'
	) }}
),

i_hwci as (
    select *
    from {{ source
	('foundlay__wholesale', 'h_wholesale_customer_invoice'
	) }}
),

i_lwcilsklu as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_line_stock_keeping_logistic_unit'
	) }}
),

i_lwcildlu as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_line_deliv_logistic_unit'
	) }}
),

i_lwcildi as (
    select *
    from {{ source
	('foundlay__wholesale', 'l_wholesale_customer_invoice_line_deliv_item'
	) }}
),

i_logistic_unit as (
    select *
    from {{ source
	('foundlay__logistic_unit', 'h_logistic_unit'
	) }}
),

i_item as (
    select *
    from {{ source
	('foundlay__item', 'h_item'
	) }}
)

select
i_hwci.wholesale_customer_invoice_no as wholesale_customer_invoice_no,
       i_hwci.h_wholesale_customer_invoice_key,
       "N" as credit_flag,
       i_swci.cust_no,
       i_swci.store_id,
       farm_fingerprint(cast(i_swci.store_id as STRING)) as d_store_key,
       i_swci.invoice_dt,
       i_swci.invoice_due_dt,
       cast(null as DATE) as cred_inv_dt,
       cast(i_logistic_unit.logistic_unit_id as INT64) as logistic_unit_id,
       i_logistic_unit.h_logistic_unit_key as h_logistic_unit_invoicing_key,
       i_hwcil.wholesale_customer_invoice_line_no,
       i_hwcil.h_wholesale_customer_invoice_line_key,
       store.store_orderable_item_id,
       store.h_store_orderable_item_key as d_store_orderable_item_key,
       i_item.item_id as global_trade_item_number,
       i_item.h_item_key as d_item_key,
       i_logistic_unit.logistic_unit_id as logistic_unit_deliv_id,
       i_logistic_unit.h_logistic_unit_key as d_logistic_unit_deliv_key,
       i_logistic_unit.logistic_unit_id as logistic_unit_stock_keeping_id,
       i_logistic_unit.h_logistic_unit_key as d_logistic_unit_stock_keeping_key,
       i_swcil.qty_soi_ordered as qty_store_orderable_items_ordered,
       i_swcil.qty_soi_delivered as qty_store_orderable_items_delivered,
       null as qty_global_trade_items_invoiced,
       i_swcil.weight_delivered,
       i_swcil.inv_line_sum as invoice_line_sum,
       i_swcil.inv_line_vat as invoice_line_vat,
       i_swcil.weight_type,
       i_swcil.sales_type,
       i_swcil.sales_type_desc,
       i_swcil.order_type,
       i_swcil.order_type_desc,
       i_swcil.deliv_method,
       i_swcil.deliv_method_desc,
       i_swcil.order_rcvg_method,
       i_swcil.order_rcvg_method_desc,
       i_swcil.item_qty_shorted_cause,
       i_swcil.item_qty_shorted_cause_desc,
       i_swcil.qty_discount,
       i_swcil.other_discount,
       i_swcil.offer_discount,
       i_swcil.supplier_backend_discount,
       i_swcil.local_clearance_discount,
       i_swcil.exhibition_discount,
       i_swcil.manual_discount,
       i_swcil.slop_item,
       i_swcil.slop_store_orderable_item_id,
       cast(null as STRING) as crediting_reason_code,
       cast(null as STRING) as crediting_reason,
       cast(null as STRING) as credit_type_code,
       cast(null as STRING) as credit_type,
       cast(null as STRING) as credit_code,
       i_swcil.effective_dttm,

       datetime(current_timestamp(), "Europe/Stockholm") as md_insert_dttm,
       "replenishment" as md_record_source,
       "{{ invocation_id }}" as md_invocation_id
from i_hwcil
inner join i_lwcil
on i_hwcil.h_wholesale_customer_invoice_line_key = i_lwcil.h_wholesale_customer_invoice_line_key
left join i_hwci
on i_lwcil.h_wholesale_customer_invoice_key = i_hwci.h_wholesale_customer_invoice_key
left join i_swci
on i_hwci.h_wholesale_customer_invoice_key = i_swci.h_wholesale_customer_invoice_key
left join i_swcil
on i_swcil.h_wholesale_customer_invoice_line_key = i_hwcil.h_wholesale_customer_invoice_line_key
left join i_lwcilds
on i_lwcilds.h_wholesale_customer_invoice_line_key = i_hwcil.h_wholesale_customer_invoice_line_key
left join i_lwciilu
on i_lwciilu.h_wholesale_customer_invoice_key = i_hwci.h_wholesale_customer_invoice_key
left join i_lwcilsklu
on i_lwcilsklu.h_wholesale_customer_invoice_line_key = i_hwcil.h_wholesale_customer_invoice_line_key
left join i_lwcildlu
on i_lwcildlu.h_wholesale_customer_invoice_line_key = i_hwcil.h_wholesale_customer_invoice_line_key
left join i_lwcildi
on i_lwcildi.h_wholesale_customer_invoice_line_key = i_hwcil.h_wholesale_customer_invoice_line_key
left join i_item
on i_item.h_item_key = i_lwcildi.h_item_key
left join i_logistic_unit
on i_logistic_unit.h_logistic_unit_key = i_lwcilsklu.h_logistic_unit_key
left join store
on store.h_store_orderable_item_key = i_lwcilds.h_store_orderable_item_key
union all
select
cast(c_swcc.invoice_no as STRING) as wholesale_customer_invoice_no,
       farm_fingerprint(cast(c_swcc.invoice_no as STRING)) as h_wholesale_customer_invoice_key,
       "Y" as credit_flag,
       c_swcc.cust_no,
       c_swcc.store_id,
       farm_fingerprint(cast(store_id as STRING)) as d_store_key,
       cast(null as DATE) as invoice_dt,
       cast(null as DATE) as invoice_due_dt,
       c_swcc.cred_inv_dt,
       cast(null as INT64) as logistic_unit_invoicing_id,
       cast(null as INT64) as h_logistic_unit_invoicing_key,
       cast(null as STRING) as wholesale_customer_invoice_line_no,
       cast(null as INT64) as h_wholesale_customer_invoice_line_key,
       store.store_orderable_item_id,
       store.h_store_orderable_item_key as d_store_orderable_item_key,
       item.item_id as global_trade_item_number,
       item.h_item_key as d_item_key,
       logistic_unit.logistic_unit_id as logistic_unit_deliv_id,
       logistic_unit.h_logistic_unit_key as d_logistic_unit_deliv_key,
       logistic_unit.logistic_unit_id as logistic_unit_stock_keeping_id,
       logistic_unit.h_logistic_unit_key as d_logistic_unit_stock_keeping_key,
       c_swcc.qty_store_orderable_items_credited,
       null as qty_store_orderable_items_delivered,
       null as qty_global_trade_items_credited,
       c_swcc.weight_credited,
       c_swcc.credit_amt,
       null as invoice_line_vat,
       c_swcc.weight_type,
       cast(null as STRING) as sales_type,
       cast(null as STRING) as sales_type_desc,
       cast(null as STRING) as order_type,
       cast(null as STRING) as order_type_desc,
       c_swcc.deliv_method,
       c_swcc.deliv_method_desc,
       cast(null as STRING) as order_rcvg_method,
       cast(null as STRING) as order_rcvg_method_desc,
       cast(null as STRING) as item_qty_shorted_cause,
       cast(null as STRING) as item_qty_shorted_cause_desc,
       null as qty_discount,
       null as other_discount,
       null as offer_discount,
       null as supplier_backend_discount,
       null as local_clearance_discount,
       null as exhibition_discount,
       null as manual_discount,
       cast(null as STRING) as slop_item,
       cast(null as STRING) as slop_store_orderable_item_id,
       c_swcc.crediting_reason_desc as crediting_reason_code,
       c_swcc.crediting_reason as crediting_reason,
       c_swcc.credit_type_desc as credit_type_code,
       c_swcc.credit_type as credit_type,
       c_swcc.credit_code,
       c_swcc.effective_dttm,
       datetime(current_timestamp(), "Europe/Stockholm") as md_insert_dttm,
       "replenishment" as md_record_source,
       "{{ invocation_id }}" as md_invocation_id
from c_hwcc
left join c_swcc
on c_hwcc.h_wholesale_customer_crediting_key = c_swcc.h_wholesale_customer_crediting_key
left join c_lwccs
on c_hwcc.h_wholesale_customer_crediting_key = c_lwccs.h_wholesale_customer_crediting_key
left join c_lwcci
on c_hwcc.h_wholesale_customer_crediting_key = c_lwcci.h_wholesale_customer_crediting_key
left join c_lwccdlu
on c_swcc.h_wholesale_customer_crediting_key = c_lwccdlu.h_wholesale_customer_crediting_key
left join c_lwccsklu
on c_swcc.h_wholesale_customer_crediting_key = c_lwccsklu.h_wholesale_customer_crediting_key
left join item
on item.h_item_key = c_lwcci.h_item_key
left join store
on store.h_store_orderable_item_key = c_lwccs.h_store_orderable_item_key
left join logistic_unit
on logistic_unit.h_logistic_unit_key = c_lwccdlu.h_logistic_unit_key
`

Logs from CI:

==== sqlfluff ====
sqlfluff:                1.4.5 python:                 3.10.9
implementation:        cpython verbosity:                   1
dialect:              bigquery templater:                 dbt
dbt:                    =1.3.2
rules:                                all
==== readout ====
effective configured processes:  8
=== [dbt templater] Sorting Nodes...
01:51:11  Partial parse save file not found. Starting full parse.
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [dbt/models/conlaybi/replenishment/conlaybi_replenishment__f_wholesale_customer_invoice_line.sql] FAIL
L:   2 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 01]
L:   3 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 01]
L:   8 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 07]
L:   9 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 07]
L:  13 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 12]
L:  14 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 12]
L:  18 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 17]
L:  19 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 17]
L:  23 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 22]
L:  24 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 22]
L:  29 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 28]
L:  30 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 28]
L:  34 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 33]
L:  35 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 33]
L:  39 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 38]
L:  40 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 38]
L:  44 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 43]
L:  45 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 43]
L:  48 | P:   2 | L003 | Expected 0 indentations, found more than 0 [compared to
                       | line 46]
L:  50 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 49]
L:  54 | P:   2 | L003 | Expected 0 indentations, found more than 0 [compared to
                       | line 52]
L:  55 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 52]
L:  56 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 52]
L:  59 | P:   2 | L003 | Expected 0 indentations, found more than 0 [compared to
                       | line 57]
L:  60 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 57]
L:  61 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 57]
L:  65 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line [64](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L64)]
L:  66 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 64]
L:  71 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 70]
L:  72 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 70]
L:  76 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 75]
L:  77 | P:   4 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 75]
L:  81 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 80]
L:  82 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 80]
L:  86 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 85]
L:  87 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 85]
L:  91 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 90]
L:  92 | P:   4 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 90]
L:  96 | P:   2 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 95]
L:  97 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 95]
L: 101 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 100]
L: 102 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 100]
L: 106 | P:   3 | L003 | Expected 1 indentation, found less than 1 [compared to
                       | line 105]
L: 107 | P:   3 | L003 | Expected 2 indentations, found less than 1 [compared to
                       | line 105]
L: 112 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 113 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 114 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 115 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 116 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 117 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 118 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 119 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 120 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 121 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 122 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 123 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 124 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 125 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 126 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 127 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 128 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 129 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 130 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 131 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 132 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 133 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 134 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 135 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 136 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 137 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 138 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 139 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 140 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 141 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 142 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 143 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 144 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 145 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 146 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 147 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 148 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 149 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 150 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 151 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 152 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 153 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 154 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 155 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 156 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 157 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 158 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 159 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 160 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 161 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 162 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 163 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 164 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 1[65](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L65) | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 1[66](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L66) | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 1[67](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L67) | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 111]
L: 171 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 170]
L: 173 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 172]
L: 175 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 174]
L: 177 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 176]
L: 179 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 178]
L: 181 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 180]
L: 183 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 182]
L: 185 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 184]
L: 187 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 186]
L: 189 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 188]
L: 191 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 190]
L: 193 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 192]
L: 197 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 198 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 199 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 200 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 201 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 202 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 203 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 204 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 205 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 206 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 207 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 208 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 209 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 210 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 211 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 212 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 213 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 214 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 215 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 216 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 217 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 218 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 219 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 220 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 221 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 222 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 223 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 224 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 225 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 226 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 227 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 228 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 229 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 230 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 231 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 232 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 233 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 234 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 235 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 236 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 237 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 238 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 239 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 240 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 241 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 242 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 243 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 244 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 245 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 246 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 247 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 248 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 250 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 251 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 252 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 253 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 196]
L: 257 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 256]
L: 259 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 258]
L: 261 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 260]
L: 263 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 262]
L: 265 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 264]
L: 267 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 266]
L: 269 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 2[68](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L68)]
L: 271 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 2[70](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L70)]
==== summary ====
violations:      1[76](https://git.ica.ia-hc.net/bi/cloud-dw/batch-framework/bica-dbt/-/jobs/385875#L76) status:         FAIL
All Finished!
sqlfluff-fix............................................................Skipped

### How to reproduce

1. create model
2. commit and pre-commit runs and lints code (using sqlfluff)
3. Let it fix model and push code to repo
4. Let ci job run and fail on pre-commit stage.

### Dialect

bigquery

### Version

sqlfluff: 1.4.5
python: 3.8.10

### Configuration

`
[sqlfluff]
templater = dbt
dialect = bigquery
verbose = 1
# exclude_rules
# - L014=capitalisation of unquoted identifiers
# - L016=line max length
# - L027=References should be qualified if select has more than one referenced table/view. (this is invalid in BigQuery anyway.)
# - L032=prefer ON over USING in join statements
# - L034=wildcard select first
# - L038=select clause trailing commas
# - L042=forbid subqueries in join/from clauses
exclude_rules = L014,L016,L027,L032,L034,L038,L042
encoding = utf-8
large_file_skip_byte_limit = 30000

[sqlfluff:rules]
tab_space_size = 4
indent_unit = space
capitalisation_policy = lower
extended_capitalisation_policy = lower

[sqlfluff:layout:type:comma]
line_position = trailing

[sqlfluff:rules:L010]
# capitalisation of keywords.
capitalisation_policy = lower

[sqlfluff:rules:L014]
# capitalisation of unquoted identifiers
# TODO: Agree on whether this is a good idea or not
# extended_capitalisation_policy = lower

[sqlfluff:rules:L029]
# Keywords should not be used as identifiers.
# The words below are commonly used in BICA models and reports and should be ignored.
ignore_words = week,month,quarter,year,function

[sqlfluff:rules:L030]
# capitalisation of function names
extended_capitalisation_policy = lower

[sqlfluff:rules:L038]
# select clause trailing commas
# TODO: Agree on whether this is a good idea or not. (It should be optional.)
# select_clause_trailing_comma = require

[sqlfluff:rules:L040]
# capitalisation of boolean/null literal
capitalisation_policy = lower

[sqlfluff:templater:dbt]
project_dir = .
profiles_dir = .
profile = etlapp
target = tcm

[sqlfluff:templater:jinja]
apply_dbt_builtins = true
`

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by roryv-docker** [comment]
@christopherekfeldt I'm having the same issue. I saw your request was closed, did you manage to find a solution for this?

**Comment by kieronellis** [comment]
Did you figure out what was causing this?

**Comment by kieronellis** [comment]
For us it's that the compiled SQL is different locally and on the cloud with our CI tool because we're using the is_incremental() macro which outputs different compiled code depending on what's in the data warehouse.

**Comment by christopherekfeldt** [comment]
No, it runs not incremental part locally and in CI it runs the incremental part of the jinja code..
