### ISSUE TITLE
Postgres psql \gset meta-command is recognized as comment, causes unparsable section

### ISSUE THREAD

**Issue by grschafer** [sqlfluff/sqlfluff#4329]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.


### What Happened

First off, thanks for building and maintaining sqlfluff! It's great to have a tool like this so writing SQL can be a bit more consistent and maintainable. :heart: 

It looks like there have been some efforts to support psql meta-commands and variables:
- https://github.com/sqlfluff/sqlfluff/issues/1327
- https://github.com/sqlfluff/sqlfluff/issues/1534
- https://github.com/sqlfluff/sqlfluff/issues/3343

But the `\gset` meta-command is causing some problems. Here's some context on `\gset`:
- https://www.postgresql.org/docs/current/app-psql.html (and search in the page for gset)
- https://www.depesz.com/2013/02/03/waiting-for-9-3-create-a-psql-command-gset-to-store-query-results-into-psql-variables/

Notably, the `\gset` command often appears at the end of a query and in place of a semi-colon. Example:
```sql
select 'hello' as my_psql_var \gset
select :'my_psql_var';

-- Running the above in psql gives the below output
 ?column? 
----------
 hello
(1 row)
```

If I put the above sql in a file named `test.sql` and lint it with sqlfluff:
```
$ sqlfluff lint --ignore-local-config --dialect postgres test.sql
== [test.sql] FAIL                                                                                                                                                                                                                                                                
L:   2 | P:   1 |  PRS | Line 2, Position 1: Found unparsable section: "select
                       | :'my_psql_var'"
L:   2 | P:  22 | L003 | Expected 1 indentation, found 0 [compared to line 01]
WARNING: Parsing errors found and dialect is set to 'postgres'. Have you configured your dialect correctly?
All Finished 📜 🎉!
```

The parse output shows that `\gset` is being treated as a "comment":
```
$ sqlfluff parse --ignore-local-config --dialect postgres test.sql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        select_statement:
[L:  1, P:  1]      |            select_clause:
[L:  1, P:  1]      |                keyword:                                      'select'
[L:  1, P:  7]      |                [META] indent:
[L:  1, P:  7]      |                whitespace:                                   ' '
[L:  1, P:  8]      |                select_clause_element:
[L:  1, P:  8]      |                    quoted_literal:                           "'hello'"
[L:  1, P: 15]      |                    whitespace:                               ' '
[L:  1, P: 16]      |                    alias_expression:
[L:  1, P: 16]      |                        keyword:                              'as'
[L:  1, P: 18]      |                        whitespace:                           ' '
[L:  1, P: 19]      |                        naked_identifier:                     'my_psql_var'
[L:  1, P: 30]      |                whitespace:                                   ' '
[L:  1, P: 31]      |                comment:                                      '\\gset'
[L:  1, P: 36]      |                newline:                                      '\n'
[L:  2, P:  1]      |                unparsable:                                   !! Expected: 'Nothing...'
[L:  2, P:  1]      |                    raw:                                      'select'
[L:  2, P:  7]      |                    whitespace:                               ' '
[L:  2, P:  8]      |                    raw:                                      ':'
[L:  2, P:  9]      |                    single_quote:                             "'my_psql_var'"
[L:  2, P: 22]      |            [META] dedent:
[L:  2, P: 22]      |    statement_terminator:                                     ';'
[L:  2, P: 23]      |    newline:                                                  '\n'
[L:  3, P:  1]      |    [META] end_of_file:

==== parsing violations ====
L:   2 | P:   1 |  PRS | Line 2, Position 1: Found unparsable section: "select
                       | :'my_psql_var'"
WARNING: Parsing errors found and dialect is set to 'postgres'. Have you configured your dialect correctly?
```

### Expected Behaviour

I would expect most psql meta-commands that involve the current query buffer (`\g`, `\gdesc`, `\gexec`, `\gset`, `\gx`, `\w`, `\write`, `\watch`, `\crosstabview`) to act as a semi-colon rather than a comment. The [postgres docs](https://www.postgresql.org/docs/current/app-psql.html) even mention that:

> `\g` without any arguments is essentially equivalent to a semicolon

One note about these meta-commands is running them on an empty query buffer will re-execute the most recent query instead. So, the sql commands above could be written like this (note that line 1 now has a semi-colon):

```
select 'hello' as my_psql_var;
\gset
select :'my_psql_var';
```

and that passes sqlfluff linting without the "unparsable section" failure. But, that runs the first select twice, which can be undesirable -- I'm often trying to store variables on data-mutating statements like `insert ... returning field1 as varname \gset` or `select field1 as varname from function_call() \gset` where I wouldn't want to run the statement again.

### Observed Behaviour

As noted in the "What Happened" section, psql meta-commands like `\gset` act as comments instead of ending the current query buffer / statement. This behavior causes sqlfluff linting errors for most code online (in postgres docs, stackoverflow answers, blogposts, etc.) that involves these psql meta-commands.

I'm not sure why `\` is recognized as a comment. According to https://www.postgresql.org/docs/8.0/sql-syntax.html#SQL-SYNTAX-COMMENTS only `--` and `/* ... */` should be, but I'm probably missing some historical context or something.

### How to reproduce

Contents of `test.sql` file:
```
select 'hello' as my_psql_var \gset
select :'my_psql_var';
```

Commands run:
```
sqlfluff lint --ignore-local-config --dialect postgres test.sql
sqlfluff parse --ignore-local-config --dialect postgres test.sql
```

If you want to play with psql meta-commands and the above script:
```
docker run --rm --detach --name=test-psql-gset-unparsable --env=POSTGRES_PASSWORD=foo --volume=$(pwd):/curdir:ro postgres:15
docker exec -it --workdir=/curdir test-psql-gset-unparsable psql -U postgres

# This will give you the psql prompt, you can run test.sql with `\i` like below:
postgres=# \i test.sql
# To exit, do `\q`:
postgres=# \q

# To stop the postgres container
docker stop test-psql-gset-unparsable
```

### Dialect

Postgres

### Version

```
$ sqlfluff --version
sqlfluff, version 1.4.5

$ python --version
Python 3.11.1
```

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
The historical context is essentially that we shoved them in as comments until we could decide how we wanted to handle them. Moving the query buffer metas out of that seems like a fairly sensible first step
