### ISSUE TITLE
Support unimplemented / incomplete BigQuery DDLs

### ISSUE THREAD

**Issue by kzosabe** [sqlfluff/sqlfluff#5789]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

As I use sqlfluff in my work, I've noticed that there are many grammars that have not yet been implemented in BigQuery dialect.
I'm planning to try to implement them little by little.
In the first, I would like to aim to be able to parse all DDLs that currently exist in the official documentation.

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language

### TODOs

- [x] CREATE SCHEMA statement
- [x] CREATE TABLE statement
- [x] CREATE TABLE LIKE statement
- [x] CREATE TABLE COPY statement
- [x] CREATE SNAPSHOT TABLE statement
- [x] CREATE TABLE CLONE statement
- [x] CREATE VIEW statement
- [x] CREATE MATERIALIZED VIEW statement
- [x] CREATE MATERIALIZED VIEW AS REPLICA OF statement
- [x] CREATE EXTERNAL TABLE statement
- [x] CREATE FUNCTION statement

- [ ] CREATE TABLE FUNCTION statement
  - in progress
    - https://github.com/sqlfluff/sqlfluff/pull/5480
    - https://github.com/sqlfluff/sqlfluff/issues/5009
 
- [x] CREATE PROCEDURE statement
- [x] CREATE ROW ACCESS POLICY statement
- [x] CREATE CAPACITY statement
- [x] CREATE RESERVATION statement
- [x] CREATE ASSIGNMENT statement
- [x] CREATE SEARCH INDEX statement
- [x] CREATE VECTOR INDEX statement
- [x] ALTER SCHEMA SET DEFAULT COLLATE statement
- [x] ALTER SCHEMA SET OPTIONS statement
- [x] ALTER SCHEMA ADD REPLICA statement
- [x] ALTER SCHEMA DROP REPLICA statement
- [x] ALTER TABLE SET OPTIONS statement
- [x] ALTER TABLE ADD COLUMN statement
- [x] ALTER TABLE ADD FOREIGN KEY statement
- [x] ALTER TABLE ADD PRIMARY KEY statement
- [x] ALTER TABLE RENAME TO statement
- [x] ALTER TABLE RENAME COLUMN statement
- [x] ALTER TABLE DROP COLUMN statement
- [x] ALTER TABLE DROP CONSTRAINT statement
- [x] ALTER TABLE DROP PRIMARY KEY statement
- [x] ALTER TABLE SET DEFAULT COLLATE statement
- [x] ALTER COLUMN SET OPTIONS statement
- [x] ALTER COLUMN DROP NOT NULL statement
- [x] ALTER COLUMN SET DATA TYPE statement
- [x] ALTER COLUMN SET DEFAULT statement
- [x] ALTER COLUMN DROP DEFAULT statement
- [x] ALTER VIEW SET OPTIONS statement
- [x] ALTER MATERIALIZED VIEW SET OPTIONS statement

- [x] ALTER ORGANIZATION SET OPTIONS statement
  -  not implemented

unparsable valid sql example:
```sql
ALTER ORGANIZATION
SET OPTIONS (`region-us.default_time_zone`="Asia/Tokyo");
```

- [x] ALTER PROJECT SET OPTIONS statement
  -  not implemented

unparsable valid sql example:
```sql
ALTER PROJECT `example-project`
SET OPTIONS (`region-us.default_time_zone`="Asia/Tokyo");
```

- [x] ALTER BI_CAPACITY SET OPTIONS statement
  -  not implemented

unparsable valid sql example:
```
ALTER BI_CAPACITY `example-project.region-us.default`
SET OPTIONS(size_gb = 250);
```

- [x] ALTER CAPACITY SET OPTIONS statement
  -  not implemented

unparsable valid sql example:
```
ALTER CAPACITY `example-project.region-us.example_commitment`
SET OPTIONS (plan = "THREE_YEAR");
```

- [x] ALTER RESERVATION SET OPTIONS statement
  -  not implemented

unparsable valid sql example:
```
ALTER RESERVATION `example-project.region-us.example_reservation`
SET OPTIONS (slot_capacity=123);
```

- [x] DROP SCHEMA statement
- [x] UNDROP SCHEMA statement
- [x] DROP TABLE statement
- [x] DROP SNAPSHOT TABLE statement
- [x] DROP EXTERNAL TABLE statement
- [x] DROP VIEW statement
- [x] DROP MATERIALIZED VIEW statement
- [x] DROP FUNCTION statement
- [x] DROP TABLE FUNCTION statement
- [x] DROP PROCEDURE statement

- [ ] DROP ROW ACCESS POLICY statement
  -  not implemented

unparsable valid sql example:
```
DROP ROW ACCESS POLICY
example_policy_name ON example_dataset.example_table;
```

- [ ] DROP CAPACITY statement
  -  not implemented

unparsable valid sql example:
```
DROP CAPACITY `example-project.region-us.example_commitment`;
```

- [ ] DROP RESERVATION statement
  -  not implemented

unparsable valid sql example:
```
DROP RESERVATION `example-project.region-us.example_reservation`;
```

- [ ] DROP ASSIGNMENT statement
  -  not implemented

unparsable valid sql example:
```
DROP ASSIGNMENT `example-project.region-us.example_reservation.example_assignment`;
```

- [ ] DROP SEARCH INDEX statement
  -  not implemented

unparsable valid sql example:
```
DROP SEARCH INDEX example_index ON example_dataset.example_table;
```

- [ ] DROP VECTOR INDEX statement
  -  not implemented

unparsable valid sql example:
```
DROP VECTOR INDEX example_index ON example_dataset.example_table;
```

### Use case

I think implementing these would be beneficial to users of BigQuery dialect.
So the goal is to have all of the above checkboxes filled.

### Dialect

BigQuery

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by kzosabe** [comment]
Since there is already a wip PR to fix `CREATE TABLE FUNCTION` and a separate issue, I'll mark this issue as completed.
Thanks for participating and for the many reviews. Closed.
